# Backend abstraction over XmlStructPugixml (pugixml via ccall) - the winner of the Phase 2
# bake-off (bench/results/, decided 2026-07-04): fastest on both small fixtures and the large
# 20k-record synthetic fixture. Node/attribute handles are pugixml's own internal pointers
# (Ptr{Cvoid}), obtained via XmlStructPugixml's shim - views into the parsed document's memory
# pool, valid only until the owning document is freed.
UnifiedXMLElement = Ptr{Cvoid}

# pugixml is not namespace-aware: pugishim_node_name returns the literal tag text, e.g.
# "TestComplexAndSimple:document", not just "document". Struct field/type names generated by
# XsdToStruct.jl never carry the namespace prefix, so it must be stripped here - this is the one
# place every node's field-symbol lookup (tag_symbol(name(...))) depends on.
function name(node::Ptr{Cvoid})::String
    raw = XmlStructPugixml.node_name(node)
    idx = findlast(==(':'), raw)
    return isnothing(idx) ? raw : raw[(idx + 1):end]
end

content(node::Ptr{Cvoid})::String = strip(XmlStructPugixml.node_text(node))

haschildren(node::Ptr{Cvoid})::Bool = XmlStructPugixml.has_element_children(node)

"""
	getattributes_dict(x::UnifiedXMLElement)

All of `x`'s attributes as a `Dict{String,String}`, keyed by their literal name (pugixml is not
namespace-aware, so a prefixed attribute like `xsi:schemaLocation` keeps its prefix, and an
`xmlns:*` declaration appears as an ordinary attribute rather than being resolved/excluded).
"""
getattributes_dict(x::Ptr{Cvoid})::Dict{String, String} = XmlStructPugixml.each_attribute(x)

function readxmlfile(f::Function, filename::AbstractString)
    @debug "Loading with pugixml..."
    doc = XmlStructPugixml.parse_file(filename)
    doc == C_NULL && error("pugixml failed to parse $filename")
    try
        return f(doc)
    finally
        XmlStructPugixml.free_doc(doc)
    end
end

function readxmlfile(f::Function, io::IO)
    @debug "Loading with pugixml..."
    doc = XmlStructPugixml.parse_buffer(read(io))
    doc == C_NULL && error("pugixml failed to parse XML from IO")
    try
        return f(doc)
    finally
        XmlStructPugixml.free_doc(doc)
    end
end

docroot(doc_handle::Ptr{Cvoid})::Ptr{Cvoid} = XmlStructPugixml.root(doc_handle)

mutable struct XmlStructLoaderNode{XML <: UnifiedXMLElement, T <: Union{DataType, Union}}
    node::XML
    type::T
    parent::Union{Nothing, XmlStructLoaderNode{XML}}
    children::Vector{XmlStructLoaderNode{XML}}
    next_sibling::Union{Nothing, XmlStructLoaderNode{XML}}
end

# xml_parser_in_module.jl's construct_xml_node_child_objects keys its `fields` accumulator dict
# by the *raw* node (`AbstractTrees.parent(xml_child)`), not the XmlStructLoaderNode wrapper - this
# map backs that lookup. Ptr{Cvoid} is isbits, so this dict is a normal fast hash map (unlike
# XML.jl's LazyNode, which measured ~500-1000x slower as an IdDict key since it isn't isbits - see
# commit ee9fbc3, "Investigate lazy-loading backends"). Reset once per document at the top of tree
# construction (see the parent===nothing XmlStructLoaderNode constructor below).
const _raw_parent_map = IdDict{Ptr{Cvoid}, Ptr{Cvoid}}()
AbstractTrees.parent(node::Ptr{Cvoid}) = _raw_parent_map[node]

const EMPTY_CHILDREN = XmlStructLoaderNode{Ptr{Cvoid}}[]

function _build_node_tree(
        raw::Ptr{Cvoid},
        type::T,
        parent::Union{Nothing, XmlStructLoaderNode{Ptr{Cvoid}}},
    ) where {T}
    self = XmlStructLoaderNode{Ptr{Cvoid}, T}(raw, type, parent, EMPTY_CHILDREN, nothing)
    kids_raw = XmlStructPugixml.element_children(raw)
    isempty(kids_raw) && return self
    kids = Vector{XmlStructLoaderNode{Ptr{Cvoid}}}(undef, length(kids_raw))
    for (i, craw) in enumerate(kids_raw)
        _raw_parent_map[craw] = raw
        ctype = get_base_field_type(type, tag_symbol(name(craw)))
        kids[i] = _build_node_tree(craw, ctype, self)
    end
    self.children = kids
    for i in 1:(length(kids) - 1)
        kids[i].next_sibling = kids[i + 1]
    end
    return self
end

# The parent===nothing entry point uniquely marks the start of a new document's node tree (every
# recursive call below passes a real XmlStructLoaderNode as parent), so this is where the raw
# parent map gets reset for the new document.
function XmlStructLoaderNode(node::Ptr{Cvoid}, type, ::Nothing)
    empty!(_raw_parent_map)
    return _build_node_tree(node, type, nothing)
end
XmlStructLoaderNode(node::Ptr{Cvoid}, type, parent::XmlStructLoaderNode) =
    XmlStructLoaderNode(node, type, parent, EMPTY_CHILDREN, nothing)

AbstractTrees.parent(node::XmlStructLoaderNode) = isnothing(node.parent) ? node.node : node.parent
AbstractTrees.isroot(node::XmlStructLoaderNode) = isnothing(node.parent)
AbstractTrees.children(node::XmlStructLoaderNode) = node.children

# AbstractTrees Iterators
Base.IteratorEltype(::Type{<:TreeIterator{<:XmlStructLoaderNode}}) = Base.HasEltype()
Base.eltype(::Type{<:TreeIterator{T}}) where {T <: XmlStructLoaderNode} = T

AbstractTrees.ParentLinks(::Type{<:XmlStructLoaderNode}) = AbstractTrees.ImplicitParents()
AbstractTrees.SiblingLinks(::Type{<:XmlStructLoaderNode}) = AbstractTrees.StoredSiblings()

AbstractTrees.nextsibling(node::XmlStructLoaderNode) = node.next_sibling

function _get_default(@nospecialize(ParentType::Type), @nospecialize(child::UnifiedXMLElement))
    defaults = AbstractXsdTypes.defaults(ParentType)
    field = tag_symbol(name(child))
    child_default = get(defaults, field, nothing)
    return child_default
end

get_default(node::XmlStructLoaderNode) = _get_default(node.parent.type, node.node)
