# Backend abstraction over XmlStructPugixml (pugixml via ccall). Node and attribute handles are
# pugixml's own internal pointers (Ptr{Cvoid}), obtained through XmlStructPugixml's shim: views
# into the parsed document's memory pool, valid only until the owning document is freed.
UnifiedXMLElement = Ptr{Cvoid}

# pugixml is not namespace-aware: pugishim_node_name returns the literal tag text, e.g.
# "TestComplexAndSimple:document", not just "document". Struct field/type names generated by
# XsdToStruct.jl never carry the namespace prefix, so it must be stripped here - this is the one
# place every node's field-symbol lookup (name_symbol) depends on.
function name(node::Ptr{Cvoid})::String
    raw = XmlStructPugixml.node_name(node)
    idx = findlast(==(':'), raw)
    return isnothing(idx) ? raw : raw[(idx + 1):end]
end

content(node::Ptr{Cvoid})::String = strip(XmlStructPugixml.node_text(node))

"""
	name_symbol(node::UnifiedXMLElement)::Symbol

The node's tag name as a `Symbol`, with any namespace prefix stripped: the struct-field lookup
key for `node`, and the `Symbol` form of what `name` returns as a `String`.

Interned from pugixml's own name bytes rather than built from a `String`, because this runs
several times per node visited and the `String` would be hashed once and discarded.
"""
function name_symbol(node::Ptr{Cvoid})::Symbol
    ptr = XmlStructPugixml.node_name_ptr(node)
    ptr == C_NULL && return Symbol("")
    colon = ccall(:strrchr, Ptr{UInt8}, (Ptr{UInt8}, Cint), ptr, Int32(':'))
    return ccall(:jl_symbol, Ref{Symbol}, (Cstring,), colon == C_NULL ? ptr : colon + 1)
end

haschildren(node::Ptr{Cvoid})::Bool = XmlStructPugixml.has_element_children(node)

"""
	getattributes_dict(x::UnifiedXMLElement)

All of `x`'s attributes as a `Dict{String,String}`, keyed by their literal name (pugixml is not
namespace-aware, so a prefixed attribute like `xsi:schemaLocation` keeps its prefix, and an
`xmlns:*` declaration appears as an ordinary attribute rather than being resolved/excluded).
"""
getattributes_dict(x::Ptr{Cvoid})::Dict{String, String} = XmlStructPugixml.each_attribute(x)

# pugixml decodes UTF-8, UTF-16 and UTF-32. A document declaring anything else is read as raw
# bytes, which turns non-ASCII text into invalid `String`s rather than failing, so the declaration
# is checked before the parse.
function _warn_unsupported_encoding(declaration::AbstractString, source::AbstractString)::Nothing
    m = match(r"encoding\s*=\s*[\"']([^\"']+)[\"']", declaration)
    isnothing(m) && return nothing
    encoding = uppercase(m.captures[1])
    startswith(encoding, "UTF") && return nothing
    @warn "pugixml decodes UTF-8, UTF-16 and UTF-32 only; text in $source may be read incorrectly" declaration = encoding
    return nothing
end

function readxmlfile(f::Function, filename::AbstractString)
    @debug "Loading with pugixml..."
    open(filename) do probe
        _warn_unsupported_encoding(String(read(probe, 128)), filename)
    end
    doc = XmlStructPugixml.parse_file(filename)
    doc == C_NULL && error("pugixml failed to parse $filename")
    try
        return f(doc)
    finally
        XmlStructPugixml.free_doc(doc)
    end
end

function readxmlfile(f::Function, io::IO)
    @debug "Loading with pugixml..."
    bytes = read(io)
    _warn_unsupported_encoding(String(bytes[1:min(128, end)]), "this document")
    doc = XmlStructPugixml.parse_buffer(bytes)
    doc == C_NULL && error("pugixml failed to parse XML from IO")
    try
        return f(doc)
    finally
        XmlStructPugixml.free_doc(doc)
    end
end

docroot(doc_handle::Ptr{Cvoid})::Ptr{Cvoid} = XmlStructPugixml.root(doc_handle)
