name = "XmlStructPugixml"
uuid = "69c5dbe4-038b-4614-a603-8f259d1fd840"
version = "0.1.0"
authors = ["Tom Lemmens", "Jorge Vieyra"]

[deps]
pugixml_jll = "ef860afa-341e-548b-93de-15e6b165854a"

[compat]
julia = "1.6"
pugixml_jll = "1.16"
