module XmlStructLoader

using Reexport
using Dates
using Base64
using PrecompileTools
using TimeZones
using Parsers
using Memoization
import XmlStructPugixml
using AbstractXsdTypes

include(joinpath("xml_parser", "xml_parser.jl"))
include("xml_module_utilities.jl")
include("precompilation.jl")

export load, import_module_from_xml, use_module_from_xml

"""
	load(xml_path::AbstractString, module_ref::Module; validate::Bool=true)

Load the given XML file into the structs defined in the given module and return the loaded struct.
The module has to be generated by XsdToStruct.jl.
By default the loader will validate if the data in the given XML conforms to the restrictions specified in the XSD.
To skip this validation the keyword argument `validate`` can be set to false.

# Examples
```julia-repl
julia> using XmlStructLoader
julia> include(joinpath("path", "to", "xsd", "module.jl"))
julia> using .XsdModule
julia> load(joinpath("path", "to", "xml", "file.xml"), XsdModule)
```
or:
```julia-repl
julia> using XmlStructLoader
julia> include(joinpath("path", "to", "xsd", "module.jl"))
julia> import .XsdModule
julia> load(joinpath("path", "to", "xml", "file.xml"), XsdModule)
```
or to skip validation:
```julia-repl
julia> using XmlStructLoader
julia> include(joinpath("path", "to", "xsd", "module.jl"))
julia> using .XsdModule
julia> load(joinpath("path", "to", "xml", "file.xml"), XsdModule, validate=false)
```
"""
function load(xml_path::AbstractString, module_ref::Module; validate::Bool = true)
    local loaded_xml
    open(xml_path) do xml_io
        return loaded_xml = load(xml_io, module_ref, validate = validate)
    end
    return loaded_xml
end

load(xml_io::IO, module_ref::Module; validate::Bool = true) =
    Base.@invokelatest construct_xml_object(xml_io, module_ref, validate = validate)

"""
	load(xml_path::AbstractString, module_path::AbstractString; validate::Bool=true)

Load the given XML file into the structs defined in the given module and return the loaded struct.
The module has to be generated by XsdToStruct.jl.
By default the loader will validate if the data in the given XML conforms to the restrictions specified in the XSD.
To skip this validation the keyword argument `validate` can be set to false.

# Examples
```julia-repl
julia> using XmlStructLoader
julia> load(joinpath("path", "to", "xml", "file.xml"), joinpath("path", "to", "xsd", "module.jl"))
```
"""
function load(xml_path::AbstractString, module_path::AbstractString; validate::Bool = true)
    local loaded_xml
    open(xml_path) do xml_io
        return loaded_xml = load(xml_io, module_path, validate = validate)
    end
    return loaded_xml
end

function load(xml_io::IO, module_path::AbstractString; validate::Bool = true)
    module_ref = import_module_from_xml(xml_io, module_path)
    loaded_xml = Base.@invokelatest construct_xml_object(xml_io, module_ref, validate = validate)
    return loaded_xml
end

"""
	import_module_from_xml(xml_path::AbstractString, module_path::AbstractString)::Module

Import the module from the .jl files in the module_path and return a reference to this module.
This reference can be passed into the load function.

# Examples
```julia-repl
julia> using XmlStructLoader
julia> module_ref = import_module_from_xml(path/to/xml/file.xml, path/to/module/module.jl)
```
"""
function import_module_from_xml(xml_path::AbstractString, module_path::AbstractString)::Module
    module_ref = open(xml_path) do xml_io
        return import_module_from_xml(xml_io, module_path)
    end
    return module_ref
end

function import_module_from_xml(xml_io::IO, module_path::AbstractString)::Module
    module_file = get_module_file_path(module_path)
    return import_module(module_file, module_symbol_in_file(module_file))
end

"""
	use_module_from_xml(xml_path::AbstractString, module_path::AbstractString)::Module

Use the module from the .jl files in the module_path and return a reference to this module.
This reference can be passed into the load function.

# Examples
```julia-repl
julia> using XmlStructLoader
julia> module_ref = use_module_from_xml(path/to/xml/file.xml, path/to/module/module.jl)
```
"""
function use_module_from_xml(xml_path::AbstractString, module_path::AbstractString)::Module
    module_ref = open(xml_path) do xml_io
        return use_module_from_xml(xml_io, module_path)
    end
    return module_ref
end

function use_module_from_xml(xml_io::IO, module_path::AbstractString)::Module
    module_file = get_module_file_path(module_path)
    return use_module(module_file, module_symbol_in_file(module_file))
end

"""
	precompile_schema(module_ref::Module, sample::AbstractString)
	precompile_schema(module_ref::Module)

Load `sample` into the schema in `module_ref` while the package holding that module is
precompiling, so the code this loader compiles for the schema's types is kept in the package image
instead of being compiled again in every session.

Call it at the top level of the package that carries a generated module:

```julia
module MyMessages
import XmlStructLoader
include("pacs_008_001_09.jl")
XmlStructLoader.precompile_schema(
    pacs_008_001_09,
    read(joinpath(@__DIR__, "..", "sample", "message.xml"), String),
)
end
```

Measured on a 161-type ISO 20022 schema: the first `load` of a session costs about 24 ms with
this, and about 3.6 s without, for roughly a second of extra precompilation. Later loads are
unaffected - they were never the slow part.

`sample` wants to be a document that exercises the parts of the schema a caller reads, because a
workload caches exactly the calls it makes: this one covers a file path and an `IO`, with and
without validation, and nothing else. A caller who loads through their own wrapper can cache that
too, with a `PrecompileTools.@compile_workload` of their own.

Calling this is the opt-in; a package that does not want the extra precompilation simply does not
call it. The single-argument form reads the sample from `module_ref.__meta.precompile_sample`, for
generated modules that carry one.

A sample that cannot be loaded warns rather than failing the build: a broken workload should cost
latency, not an install.
"""
function precompile_schema(module_ref::Module, sample::AbstractString)
    PrecompileTools.@compile_workload begin
        try
            # Each entry compiles its own code: a path and an `IO` are different methods, and
            # validating differs from not. Caching one leaves the others for the caller's session.
            mktempdir() do dir
                path = joinpath(dir, "precompile_sample.xml")
                write(path, sample)
                load(path, module_ref, validate = false)
                load(path, module_ref, validate = true)
            end
            load(IOBuffer(sample), module_ref, validate = false)
            load(IOBuffer(sample), module_ref, validate = true)
        catch err
            @warn "precompile workload for $module_ref did not complete" exception = err
        end
    end
    return nothing
end

function precompile_schema(module_ref::Module)
    sample = try
        module_ref.__meta.precompile_sample
    catch
        @warn "$module_ref carries no precompile sample; pass a document to precompile_schema"
        return nothing
    end
    return precompile_schema(module_ref, sample)
end

end # module XmlStructLoader
