name = "AbstractXsdTypes"
uuid = "1d4aff4b-e088-40cb-b713-ffe4caf1580b"
authors = ["Tom Lemmens", "Matthijs Cox"]
version = "0.1.0"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"

[compat]
Format = "1"
