name = "AbstractXsdTypes"
uuid = "894546dd-dc3f-42e8-9b69-a7785ccf72be"
authors = ["Tom Lemmens", "Matthijs Cox"]
version = "0.1.0"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"

[compat]
julia = "1.6"
Format = "1"
Memoization = "0.2"
