name: Test
# Run on master, tags, or any pull request
on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  push:
    branches: [main]
    tags: '*'
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6' # Latest LTS
          - '1' # Latest stable 1.x
        os:
        - ubuntu-latest
        - windows-latest
        arch:
          - x64
    uses: ./.github/workflows/TestWithInputs.yml
    with:
          version: ${{ matrix.version }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}